services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: books
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: admin
    